java:
  applicationPort: 8080
  image: 'hmctssandbox.azurecr.io/labs/beardfacekainos:latest'
  ingressHost: labs-beardfacekainos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: labs
  environment:
